using System.Security.Cryptography;
using System.Text;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Atlantis.Cli.Commands;

internal record ExportedMethod(string ClassName, string MethodName, string ReturnType, List<MethodParameter> Parameters, string SourceFile);
internal record MethodParameter(string Name, string Type);

/// <summary>
/// Scans a project directory for [AtlExport] methods and derives a stable hash of
/// the binding contract. The hash is embedded in generated bindings so staleness
/// can be detected by content (not timestamps), which survives checkouts and copies.
/// </summary>
internal static class ExportScanner
{
    public const string HeaderPrefix = "// Auto-generated by atl bindgen";
    private const string HashMarker = "inputs-sha256:";

    // With UseArtifactsOutput enabled (the Atlantis default) a project directory holds
    // only real source, but guard against stray build output regardless.
    private static readonly string[] ExcludedDirs = { "bin", "obj", "artifacts", "node_modules", ".git" };

    public static async Task<List<ExportedMethod>> ScanAsync(string sourceDir)
    {
        var exports = new List<ExportedMethod>();

        foreach (var file in EnumerateSourceFiles(sourceDir))
        {
            var code = await File.ReadAllTextAsync(file);
            var tree = CSharpSyntaxTree.ParseText(code);
            var root = await tree.GetRootAsync();

            foreach (var classDecl in root.DescendantNodes().OfType<ClassDeclarationSyntax>())
            {
                var className = classDecl.Identifier.Text;

                var methods = classDecl.Members
                    .OfType<MethodDeclarationSyntax>()
                    .Where(m => m.AttributeLists
                        .SelectMany(al => al.Attributes)
                        .Any(a => a.Name.ToString() is "AtlExport" or "AtlExportAttribute"));

                foreach (var method in methods)
                {
                    var parameters = method.ParameterList.Parameters
                        .Select(p => new MethodParameter(
                            p.Identifier.Text,
                            p.Type?.ToString() ?? "object"))
                        .ToList();

                    exports.Add(new ExportedMethod(
                        className,
                        method.Identifier.Text,
                        method.ReturnType.ToString(),
                        parameters,
                        file));
                }
            }
        }

        return exports;
    }

    private static IEnumerable<string> EnumerateSourceFiles(string sourceDir)
    {
        return Directory.EnumerateFiles(sourceDir, "*.cs", SearchOption.AllDirectories)
            .Where(f => !IsExcluded(f, sourceDir));
    }

    private static bool IsExcluded(string file, string root)
    {
        var rel = Path.GetRelativePath(root, file);
        var segments = rel.Split(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);
        return segments.Any(s => ExcludedDirs.Contains(s, StringComparer.OrdinalIgnoreCase));
    }

    /// <summary>
    /// Hashes the binding <em>contract</em> (class/method/param/return shapes), not raw
    /// file bytes, so only API-shape changes mark bindings stale — comments and
    /// formatting elsewhere do not.
    /// </summary>
    public static string ComputeInputHash(IEnumerable<ExportedMethod> exports)
    {
        var sb = new StringBuilder();
        foreach (var e in exports
            .OrderBy(e => e.ClassName, StringComparer.Ordinal)
            .ThenBy(e => e.MethodName, StringComparer.Ordinal)
            .ThenBy(e => string.Join(",", e.Parameters.Select(p => p.Type + " " + p.Name)), StringComparer.Ordinal))
        {
            sb.Append(e.ClassName).Append('.').Append(e.MethodName).Append('(');
            sb.Append(string.Join(",", e.Parameters.Select(p => p.Type + ' ' + p.Name)));
            sb.Append("):").Append(e.ReturnType).Append('\n');
        }

        var hash = SHA256.HashData(Encoding.UTF8.GetBytes(sb.ToString()));
        return Convert.ToHexString(hash).ToLowerInvariant()[..16];
    }

    public static string HeaderLine(string hash) =>
        $"{HeaderPrefix} [{HashMarker}{hash}] - DO NOT EDIT";

    /// <summary>Extract the embedded contract hash from a previously generated file.</summary>
    public static string? ReadEmbeddedHash(string filePath)
    {
        if (!File.Exists(filePath))
            return null;

        using var reader = new StreamReader(filePath);
        for (var i = 0; i < 3 && reader.ReadLine() is { } line; i++)
        {
            var idx = line.IndexOf(HashMarker, StringComparison.Ordinal);
            if (idx < 0)
                continue;

            var start = idx + HashMarker.Length;
            var end = line.IndexOf(']', start);
            if (end > start)
                return line[start..end].Trim();
        }

        return null;
    }

    /// <summary>
    /// Warn (without blocking) when a project's [AtlExport] surface no longer matches
    /// its generated frontend/&lt;name&gt;.bindings.ts files. Called by 'atl run' and
    /// 'atl build'. Reports both stale/missing bindings and orphaned bindings whose
    /// source file no longer has any [AtlExport] methods.
    /// </summary>
    public static async Task WarnIfBindingsStaleAsync(string projectDir)
    {
        var exports = await ScanAsync(projectDir);
        var frontendDir = Path.Combine(projectDir, "frontend");

        // Expected: one <name>.bindings.ts per source file, carrying a hash of that
        // file's export contract.
        var expected = exports
            .GroupBy(e => e.SourceFile)
            .ToDictionary(
                g => Path.GetFileNameWithoutExtension(g.Key) + ".bindings.ts",
                ComputeInputHash,
                StringComparer.Ordinal);

        var existing = Directory.Exists(frontendDir)
            ? Directory.EnumerateFiles(frontendDir, "*.bindings.ts")
                .Select(Path.GetFileName)
                .OfType<string>()
                .ToHashSet(StringComparer.Ordinal)
            : new HashSet<string>(StringComparer.Ordinal);

        var stale = expected
            .Where(kvp => ReadEmbeddedHash(Path.Combine(frontendDir, kvp.Key)) is not { } h
                          || !string.Equals(h, kvp.Value, StringComparison.Ordinal))
            .Select(kvp => kvp.Key)
            .OrderBy(n => n, StringComparer.Ordinal)
            .ToList();

        var orphaned = existing
            .Where(n => !expected.ContainsKey(n))
            .OrderBy(n => n, StringComparer.Ordinal)
            .ToList();

        if (stale.Count > 0)
            Console.Error.WriteLine($"warning: bindings out of date for {string.Join(", ", stale)}; run 'atl bindgen'.");

        if (orphaned.Count > 0)
            Console.Error.WriteLine($"warning: orphaned bindings {string.Join(", ", orphaned)} no longer match any [AtlExport] source; run 'atl bindgen'.");
    }
}
