using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Atlantis.Cli.Commands;

public static class GenerateCommand
{
    public static async Task<int> RunAsync(string? source, string? output)
    {
        var sourceDir = source ?? Directory.GetCurrentDirectory();
        var outputDir = output ?? Directory.GetCurrentDirectory();

        Console.WriteLine($"Scanning {sourceDir} for [JSExport] methods...");

        var exports = await ParseExports(sourceDir);

        if (exports.Count == 0)
        {
            Console.WriteLine("No [JSExport] methods found.");
            return 0;
        }

        Console.WriteLine($"Found {exports.Count} exported method(s) in {exports.Select(e => e.ClassName).Distinct().Count()} class(es).");

        // Generate files
        var jsPath = Path.Combine(outputDir, "atlantis.js");
        var dtsPath = Path.Combine(outputDir, "atlantis.d.ts");

        await File.WriteAllTextAsync(jsPath, GenerateJavaScript(exports));
        await File.WriteAllTextAsync(dtsPath, GenerateTypeScript(exports));

        Console.WriteLine($"✓ Generated {jsPath}");
        Console.WriteLine($"✓ Generated {dtsPath}");
        
        return 0;
    }

    private static async Task<List<ExportedMethod>> ParseExports(string sourceDir)
    {
        var exports = new List<ExportedMethod>();
        var csFiles = Directory.GetFiles(sourceDir, "*.cs", SearchOption.AllDirectories);

        foreach (var file in csFiles)
        {
            var code = await File.ReadAllTextAsync(file);
            var tree = CSharpSyntaxTree.ParseText(code);
            var root = await tree.GetRootAsync();

            var classes = root.DescendantNodes().OfType<ClassDeclarationSyntax>();

            foreach (var classDecl in classes)
            {
                var className = classDecl.Identifier.Text;

                var methods = classDecl.Members
                    .OfType<MethodDeclarationSyntax>()
                    .Where(m => m.AttributeLists
                        .SelectMany(al => al.Attributes)
                        .Any(a => a.Name.ToString() is "JSExport" or "JSExportAttribute"));

                foreach (var method in methods)
                {
                    var parameters = method.ParameterList.Parameters
                        .Select(p => new MethodParameter(
                            p.Identifier.Text,
                            p.Type?.ToString() ?? "object"))
                        .ToList();

                    exports.Add(new ExportedMethod(
                        className,
                        method.Identifier.Text,
                        method.ReturnType.ToString(),
                        parameters));
                }
            }
        }

        return exports;
    }

    private static string GenerateJavaScript(List<ExportedMethod> exports)
    {
        var sb = new System.Text.StringBuilder();
        sb.AppendLine("// Auto-generated by atl generate - DO NOT EDIT");
        sb.AppendLine();
        sb.AppendLine("const atlantis = (() => {");
        sb.AppendLine("  let _callId = 0;");
        sb.AppendLine("  const _pending = new Map();");
        sb.AppendLine();
        sb.AppendLine("  // Listen for responses from native host");
        sb.AppendLine("  window.addEventListener('message', (event) => {");
        sb.AppendLine("    const { callId, result, error } = event.data;");
        sb.AppendLine("    if (callId !== undefined && _pending.has(callId)) {");
        sb.AppendLine("      const { resolve, reject } = _pending.get(callId);");
        sb.AppendLine("      _pending.delete(callId);");
        sb.AppendLine("      if (error) reject(new Error(error));");
        sb.AppendLine("      else resolve(result);");
        sb.AppendLine("    }");
        sb.AppendLine("  });");
        sb.AppendLine();
        sb.AppendLine("  function _invoke(className, methodName, args) {");
        sb.AppendLine("    return new Promise((resolve, reject) => {");
        sb.AppendLine("      const callId = ++_callId;");
        sb.AppendLine("      _pending.set(callId, { resolve, reject });");
        sb.AppendLine("      window.external?.postMessage(JSON.stringify({ callId, className, methodName, args }));");
        sb.AppendLine("    });");
        sb.AppendLine("  }");
        sb.AppendLine();

        // Group by class
        var byClass = exports.GroupBy(e => e.ClassName);
        foreach (var group in byClass)
        {
            sb.AppendLine($"  const {group.Key} = {{");
            foreach (var method in group)
            {
                var paramNames = string.Join(", ", method.Parameters.Select(p => p.Name));
                sb.AppendLine($"    {method.MethodName}: ({paramNames}) => _invoke('{group.Key}', '{method.MethodName}', [{paramNames}]),");
            }
            sb.AppendLine("  };");
            sb.AppendLine();
        }

        sb.AppendLine("  return {");
        foreach (var className in byClass.Select(g => g.Key))
        {
            sb.AppendLine($"    {className},");
        }
        sb.AppendLine("  };");
        sb.AppendLine("})();");

        return sb.ToString();
    }

    private static string GenerateTypeScript(List<ExportedMethod> exports)
    {
        var sb = new System.Text.StringBuilder();
        sb.AppendLine("// Auto-generated by atl generate - DO NOT EDIT");
        sb.AppendLine();
        sb.AppendLine("declare namespace atlantis {");

        var byClass = exports.GroupBy(e => e.ClassName);
        foreach (var group in byClass)
        {
            sb.AppendLine($"  namespace {group.Key} {{");
            foreach (var method in group)
            {
                var tsParams = string.Join(", ", method.Parameters.Select(p => $"{p.Name}: {MapToTypeScript(p.Type)}"));
                var tsReturn = MapToTypeScript(method.ReturnType);
                sb.AppendLine($"    function {method.MethodName}({tsParams}): Promise<{tsReturn}>;");
            }
            sb.AppendLine("  }");
            sb.AppendLine();
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string MapToTypeScript(string csharpType)
    {
        return csharpType switch
        {
            "void" => "void",
            "bool" => "boolean",
            "string" => "string",
            "int" or "long" or "short" or "byte" or "float" or "double" or "decimal" => "number",
            "string[]" => "string[]",
            "int[]" or "long[]" or "float[]" or "double[]" => "number[]",
            "bool[]" => "boolean[]",
            _ when csharpType.EndsWith("[]") => "unknown[]",
            _ when csharpType.StartsWith("Task<") => MapToTypeScript(csharpType[5..^1]),
            "Task" => "void",
            _ => "unknown"
        };
    }

    private record ExportedMethod(string ClassName, string MethodName, string ReturnType, List<MethodParameter> Parameters);
    private record MethodParameter(string Name, string Type);
}
